"""init

Revision ID: 902739f1d241
Revises: 
Create Date: 2026-01-21 19:37:07.826578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '902739f1d241'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stored_object',
    sa.Column('oid', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_table('users',
    sa.Column('oid', sa.Uuid(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('oid'),
    sa.UniqueConstraint('telegram_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('push_up',
    sa.Column('oid', sa.Uuid(), nullable=False),
    sa.Column('user_oid', sa.Uuid(), nullable=False),
    sa.Column('video_oid', sa.Uuid(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_oid'], ['users.oid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_oid'], ['stored_object.oid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_index(op.f('ix_push_up_user_oid'), 'push_up', ['user_oid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_push_up_user_oid'), table_name='push_up')
    op.drop_table('push_up')
    op.drop_table('users')
    op.drop_table('stored_object')
    # ### end Alembic commands ###
