"""add telegram_video_id column

Revision ID: ed2d0c957372
Revises: c4e9f8a12b3d
Create Date: 2026-01-23 16:27:56.491697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed2d0c957372'
down_revision: Union[str, Sequence[str], None] = 'c4e9f8a12b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('push_up')
    op.create_table('push_up',
    sa.Column('oid', sa.Uuid(), nullable=False),
    sa.Column('user_oid', sa.Uuid(), nullable=False),
    sa.Column('telegram_file_id', sa.String(), nullable=False),
    sa.Column('is_video_note', sa.Boolean(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_oid'], ['users.oid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('oid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
