"""add datetime timezone

Revision ID: 81d335492936
Revises: 3ee8935898ed
Create Date: 2026-02-07 17:20:09.996649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81d335492936'
down_revision: Union[str, Sequence[str], None] = '3ee8935898ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_push_up_user_oid'), 'push_up', ['user_oid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_push_up_user_oid'), table_name='push_up')
    # ### end Alembic commands ###
